apiVersion: v1
kind: ConfigMap
metadata:
  name: alvin-config
data:
  postgresql-url: alvin-postgresql
  solr-url: solr-service
  fedora-url: fedora-service
  dataDividers: "cora jsClient alvin alvinPreview alvinTestSystem alvinProduction alvinData"
