apiVersion: v2
name: systemone
description: A Helm chart for SystemOne on Kubernetes
type: application
version: 0.2.9
appVersion: 1.21.0
dependencies:
  - name: cora
    version: 0.0.5
    repository: file://../cora
